### ISSUE TITLE
Transitioning APIs

### ISSUE THREAD

**Issue by rgbkrk** [getcarina/libcarina#14]
@thomasem and I discussed how to handle an API transition at the Magnum mid-cycle. We're not doing this yet (nor have a new API), I'm filing this solely to outline the steps we need to do.

Before we make a switch to a new versioned API:
- Introduce the API into libcarina with new unexported functions (go sanity)
- Check if new endpoint exists and aggregate resources across both API endpoints
- Bump `carina` to use those new libcarina bindings
- Get `carina` (CLI) shipped well before we turn off the old endpoint

**Comment by carolynvs** [comment]
Transition complete!
